CREATE TABLE `accounts`(`id` varchar(255)NOT NULL,`user_id` varchar(255)NOT NULL,`type` varchar(255)NOT NULL,`provider` varchar(255)NOT NULL,`provider_account_id` varchar(255)NOT NULL,`refresh_token` text,`access_token` text,`expires_at` bigint DEFAULT NULL,`token_type` varchar(255)DEFAULT NULL,`scope` varchar(255)DEFAULT NULL,`id_token` text,`session_state` varchar(255)DEFAULT NULL,PRIMARY KEY(`id`),UNIQUE KEY `provider_provider_account_id`(`provider`,`provider_account_id`),KEY `user_id`(`user_id`))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `activity_logs`(`id` int NOT NULL AUTO_INCREMENT,`user_id` int NOT NULL,`action` varchar(50)NOT NULL,`business_id` int DEFAULT NULL,`details` text,`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(`id`),KEY `user_id`(`user_id`),KEY `business_id`(`business_id`),KEY `idx_user_created`(`user_id`,`created_at`),KEY `idx_action_created`(`action`,`created_at`),KEY `idx_business_created`(`business_id`,`created_at`),CONSTRAINT `activity_logs_ibfk_1` FOREIGN KEY(`user_id`)REFERENCES `users`(`id`),CONSTRAINT `activity_logs_ibfk_2` FOREIGN KEY(`business_id`)REFERENCES `businesses`(`id`)ON DELETE SET NULL)ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb3;

CREATE TABLE `app_settings`(`id` int NOT NULL AUTO_INCREMENT,`key` varchar(100)NOT NULL,`value` text NOT NULL,`description` varchar(255)DEFAULT NULL,`created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(`id`),UNIQUE KEY `key`(`key`))ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `banks`(`id` int NOT NULL AUTO_INCREMENT,`bank_code` varchar(10)CHARACTER SET utf8mb4 NOT NULL,`bank_name` varchar(100)CHARACTER SET utf8mb4 NOT NULL,`is_popular` tinyint(1)DEFAULT '0',`is_active` tinyint(1)DEFAULT '1',`created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(`id`),UNIQUE KEY `bank_code`(`bank_code`))ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `batch_sales_data`(`id` int NOT NULL AUTO_INCREMENT,`businesses_id` int NOT NULL,`products_id` varchar(255)CHARACTER SET utf8mb4 NOT NULL,`date_start` date NOT NULL,`date_end` date NOT NULL,`price` decimal(15,2)NOT NULL,`amount` int NOT NULL,`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(`id`),KEY `idx_batch_sales_business`(`businesses_id`),KEY `idx_batch_sales_product`(`products_id`),KEY `idx_batch_sales_date_range`(`date_start`,`date_end`),CONSTRAINT `batch_sales_data_ibfk_1` FOREIGN KEY(`businesses_id`)REFERENCES `businesses`(`id`)ON DELETE CASCADE)ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `bundle_items`(`id` int NOT NULL AUTO_INCREMENT,`bundle_product_id` int NOT NULL,`category2_id` int NOT NULL,`required_quantity` int NOT NULL DEFAULT '1',`display_order` int DEFAULT '0',`created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(`id`),KEY `idx_bundle_product`(`bundle_product_id`),KEY `idx_category2`(`category2_id`),CONSTRAINT `fk_bundle_items_category2` FOREIGN KEY(`category2_id`)REFERENCES `category2`(`id`)ON DELETE CASCADE,CONSTRAINT `fk_bundle_items_product` FOREIGN KEY(`bundle_product_id`)REFERENCES `products`(`id`)ON DELETE CASCADE)ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Defines the structure of bundle products';

CREATE TABLE `business_tags`(`business_id` int NOT NULL DEFAULT '0',`tag_id` int NOT NULL DEFAULT '0',`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(`business_id`,`tag_id`),KEY `tag_id`(`tag_id`),CONSTRAINT `business_tags_ibfk_1` FOREIGN KEY(`business_id`)REFERENCES `businesses`(`id`),CONSTRAINT `business_tags_ibfk_2` FOREIGN KEY(`tag_id`)REFERENCES `tags`(`id`))ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `business_targets`(`id` int NOT NULL AUTO_INCREMENT,`business_id` int NOT NULL,`target` bigint DEFAULT NULL,`email_notification` tinyint(1)DEFAULT '0',`emails` text,`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(`id`),KEY `business_id`(`business_id`),CONSTRAINT `business_targets_ibfk_1` FOREIGN KEY(`business_id`)REFERENCES `businesses`(`id`)ON DELETE CASCADE)ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb3;

CREATE TABLE `businesses`(`id` int NOT NULL AUTO_INCREMENT,`name` varchar(255)NOT NULL,`permission_name` varchar(255)NOT NULL,`organization_id` int NOT NULL,`status` enum('active','inactive')NOT NULL DEFAULT 'active',`management_group_id` int DEFAULT NULL,`image_url` varchar(255)DEFAULT NULL,`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(`id`),UNIQUE KEY `permission_name`(`permission_name`),KEY `idx_businesses_organization`(`organization_id`),KEY `idx_businesses_management_group`(`management_group_id`),KEY `idx_businesses_status`(`status`),CONSTRAINT `businesses_ibfk_2` FOREIGN KEY(`organization_id`)REFERENCES `organizations`(`id`),CONSTRAINT `businesses_ibfk_3` FOREIGN KEY(`management_group_id`)REFERENCES `management_groups`(`id`)ON DELETE SET NULL)ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb3;

CREATE TABLE `category1`(`id` int NOT NULL AUTO_INCREMENT,`name` varchar(100)CHARACTER SET utf8mb4 NOT NULL,`description` text CHARACTER SET utf8mb4,`display_order` int DEFAULT '0',`is_active` tinyint(1)DEFAULT '1',`created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(`id`),UNIQUE KEY `unique_category1_name`(`name`),KEY `idx_category1_active`(`is_active`),KEY `idx_category1_display_order`(`display_order`))ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Main product categories(makanan,minuman,dessert,etc.)';

CREATE TABLE `category1_businesses`(`category1_id` int NOT NULL,`business_id` int NOT NULL,`created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(`category1_id`,`business_id`),KEY `idx_category1_businesses_category1`(`category1_id`),KEY `idx_category1_businesses_business`(`business_id`),CONSTRAINT `fk_category1_businesses_business` FOREIGN KEY(`business_id`)REFERENCES `businesses`(`id`)ON DELETE CASCADE,CONSTRAINT `fk_category1_businesses_category1` FOREIGN KEY(`category1_id`)REFERENCES `category1`(`id`)ON DELETE CASCADE)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Many-to-many relationship between Category I and Businesses';

CREATE TABLE `category2`(`id` int NOT NULL AUTO_INCREMENT,`name` varchar(100)CHARACTER SET utf8mb4 NOT NULL,`description` text CHARACTER SET utf8mb4,`display_order` int DEFAULT '0',`is_active` tinyint(1)DEFAULT '1',`created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(`id`),UNIQUE KEY `unique_category2_name_business`(`name`),KEY `idx_category2_active`(`is_active`),KEY `idx_category2_display_order`(`display_order`))ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Product subcategories(previously jenis field)';

CREATE TABLE `category2_businesses`(`category2_id` int NOT NULL,`business_id` int NOT NULL,`created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(`category2_id`,`business_id`),KEY `idx_category2_businesses_category2`(`category2_id`),KEY `idx_category2_businesses_business`(`business_id`),CONSTRAINT `fk_category2_businesses_business` FOREIGN KEY(`business_id`)REFERENCES `businesses`(`id`)ON DELETE CASCADE,CONSTRAINT `fk_category2_businesses_category2` FOREIGN KEY(`category2_id`)REFERENCES `category2`(`id`)ON DELETE CASCADE)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Many-to-many relationship between Category II and Businesses';

CREATE TABLE `chat_conversations`(`id` int NOT NULL AUTO_INCREMENT,`user_id` int NOT NULL,`title` varchar(255)CHARACTER SET utf8mb4 DEFAULT NULL,`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,`is_active` tinyint(1)NOT NULL DEFAULT '1',PRIMARY KEY(`id`),KEY `idx_user_id`(`user_id`),KEY `idx_created_at`(`created_at`),KEY `idx_updated_at`(`updated_at`),CONSTRAINT `chat_conversations_ibfk_1` FOREIGN KEY(`user_id`)REFERENCES `users`(`id`)ON DELETE CASCADE)ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `chat_messages`(`id` int NOT NULL AUTO_INCREMENT,`conversation_id` int NOT NULL,`role` enum('user','assistant')CHARACTER SET utf8mb4 NOT NULL,`content` mediumtext CHARACTER SET utf8mb4 NOT NULL,`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,`message_order` int NOT NULL DEFAULT '0',PRIMARY KEY(`id`),KEY `idx_conversation_id`(`conversation_id`),KEY `idx_created_at`(`created_at`),KEY `idx_message_order`(`message_order`),KEY `idx_conversation_order`(`conversation_id`,`message_order`),CONSTRAINT `chat_messages_ibfk_1` FOREIGN KEY(`conversation_id`)REFERENCES `chat_conversations`(`id`)ON DELETE CASCADE)ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `chat_metadata`(`id` int NOT NULL AUTO_INCREMENT,`conversation_id` int NOT NULL,`key` varchar(100)CHARACTER SET utf8mb4 NOT NULL,`value` mediumtext CHARACTER SET utf8mb4,`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(`id`),UNIQUE KEY `unique_conversation_key`(`conversation_id`,`key`),KEY `idx_conversation_id`(`conversation_id`),CONSTRAINT `chat_metadata_ibfk_1` FOREIGN KEY(`conversation_id`)REFERENCES `chat_conversations`(`id`)ON DELETE CASCADE)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `cl_accounts`(`id` int NOT NULL AUTO_INCREMENT,`account_code` varchar(20)CHARACTER SET utf8mb4 NOT NULL,`account_name` varchar(100)CHARACTER SET utf8mb4 NOT NULL,`contact_info` text CHARACTER SET utf8mb4,`credit_limit` decimal(10,2)DEFAULT '0.00',`current_balance` decimal(10,2)DEFAULT '0.00',`is_active` tinyint(1)DEFAULT '1',`created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(`id`),UNIQUE KEY `account_code`(`account_code`))ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `cogs`(`id` int NOT NULL AUTO_INCREMENT,`menu_code` varchar(50)CHARACTER SET utf8mb4 DEFAULT NULL,`ingredient_code` varchar(50)CHARACTER SET utf8mb4 DEFAULT NULL,`amount` decimal(10,3)NOT NULL DEFAULT '0.000',`created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(`id`),UNIQUE KEY `unique_product_ingredient`(`menu_code`,`ingredient_code`),KEY `idx_menu_code`(`menu_code`),KEY `idx_ingredient_code`(`ingredient_code`))ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Tabel COGS untuk menghubungkan produk dengan bahan baku dan jumlahnya';

CREATE TABLE `contacts`(`id` int NOT NULL AUTO_INCREMENT,`no_ktp` varchar(20)DEFAULT NULL,`nama` varchar(100)NOT NULL,`phone_number` varchar(20)DEFAULT NULL,`tgl_lahir` date DEFAULT NULL,`no_kk` varchar(20)DEFAULT NULL,`created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,`is_active` tinyint(1)DEFAULT '1',`jenis_kelamin` enum('Laki-laki','Perempuan')DEFAULT NULL,`kota` varchar(255)DEFAULT NULL,`kecamatan` varchar(255)DEFAULT NULL,`source_id` int DEFAULT NULL,`pekerjaan_id` int DEFAULT NULL,`source_lainnya` varchar(255)DEFAULT NULL,`alamat` text,`team_id` int DEFAULT NULL,PRIMARY KEY(`id`),UNIQUE KEY `no_ktp`(`no_ktp`),KEY `fk_contacts_source`(`source_id`),KEY `idx_tgl_lahir`(`tgl_lahir`),KEY `idx_no_kk`(`no_kk`),KEY `idx_jenis_kelamin`(`jenis_kelamin`),KEY `idx_kota_kecamatan`(`kota`,`kecamatan`),KEY `idx_contacts_team`(`team_id`),CONSTRAINT `contacts_ibfk_1` FOREIGN KEY(`team_id`)REFERENCES `teams`(`id`)ON DELETE SET NULL,CONSTRAINT `fk_contacts_source` FOREIGN KEY(`source_id`)REFERENCES `source`(`id`)ON DELETE SET NULL)ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `custom_targets`(`id` int NOT NULL AUTO_INCREMENT,`business_id` int NOT NULL,`name` varchar(255)NOT NULL,`target_amount` bigint NOT NULL,`start_date` date NOT NULL,`end_date` date NOT NULL,`email_notification` tinyint(1)DEFAULT '0',`emails` text,`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(`id`),KEY `business_id`(`business_id`),CONSTRAINT `custom_targets_ibfk_1` FOREIGN KEY(`business_id`)REFERENCES `businesses`(`id`)ON DELETE CASCADE)ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb3;

CREATE TABLE `customer_followups`(`id` int NOT NULL AUTO_INCREMENT,`contact_id` int NOT NULL,`activity_id` int DEFAULT NULL,`user_id` int NOT NULL,`followup_type` enum('Phone Call','Visit','Email','WhatsApp','SMS','Video Call','Other')NOT NULL,`followup_date` date NOT NULL,`notes` text,`created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,`next_followup_date` date DEFAULT NULL,`next_followup_time` time DEFAULT NULL,`status` enum('completed','scheduled','cancelled')DEFAULT 'completed',`updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(`id`),KEY `contact_id`(`contact_id`),KEY `user_id`(`user_id`),KEY `customer_followups_ibfk_2`(`activity_id`),KEY `idx_next_followup_date`(`next_followup_date`),KEY `idx_next_followup_time`(`next_followup_time`),KEY `idx_status`(`status`),CONSTRAINT `customer_followups_ibfk_1` FOREIGN KEY(`contact_id`)REFERENCES `contacts`(`id`)ON DELETE CASCADE,CONSTRAINT `customer_followups_ibfk_2` FOREIGN KEY(`activity_id`)REFERENCES `deals`(`id`)ON DELETE CASCADE,CONSTRAINT `customer_followups_ibfk_3` FOREIGN KEY(`user_id`)REFERENCES `users`(`id`)ON DELETE CASCADE)ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `deal_products`(`id` int NOT NULL AUTO_INCREMENT,`deal_id` int NOT NULL,`product_id` int NOT NULL,`quantity` int DEFAULT '1',`unit_price` decimal(15,2)DEFAULT NULL,`total_price` decimal(15,2)DEFAULT NULL,`notes` text,`created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(`id`),UNIQUE KEY `unique_deal_product`(`deal_id`,`product_id`),KEY `idx_deal_products_deal_id`(`deal_id`),KEY `idx_deal_products_product_id`(`product_id`),KEY `idx_deal_products_created_at`(`created_at`),CONSTRAINT `fk_deal_products_deal` FOREIGN KEY(`deal_id`)REFERENCES `deals`(`id`)ON DELETE CASCADE,CONSTRAINT `fk_deal_products_product` FOREIGN KEY(`product_id`)REFERENCES `products`(`id`)ON DELETE CASCADE)ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Junction table for deals and products(many-to-many)';

CREATE TABLE `deals`(`id` int NOT NULL AUTO_INCREMENT,`contact_id` int NOT NULL,`user_id` int NOT NULL,`business_id` int NOT NULL,`activity_date` date NOT NULL,`product_type` enum('restaurant','motorcycle','other')NOT NULL,`product_id` int DEFAULT NULL,`motorcycle_product_id` int DEFAULT NULL,`sales_pipeline_stage` enum('Cold','Warm','Hot','Won','Lost')NOT NULL,`financing_company` varchar(100)DEFAULT NULL,`note` text,`notes` text,`created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,`team_id` int DEFAULT NULL,`followup_count` int DEFAULT '0',PRIMARY KEY(`id`),KEY `contact_id`(`contact_id`),KEY `user_id`(`user_id`),KEY `business_id`(`business_id`),KEY `product_id`(`product_id`),KEY `motorcycle_product_id`(`motorcycle_product_id`),KEY `idx_sales_pipeline_stage`(`sales_pipeline_stage`),KEY `idx_deal_date`(`activity_date`),KEY `idx_deals_team`(`team_id`),KEY `idx_deals_followup_count`(`followup_count`),CONSTRAINT `deals_ibfk_1` FOREIGN KEY(`contact_id`)REFERENCES `contacts`(`id`)ON DELETE CASCADE,CONSTRAINT `deals_ibfk_2` FOREIGN KEY(`user_id`)REFERENCES `users`(`id`)ON DELETE CASCADE,CONSTRAINT `deals_ibfk_3` FOREIGN KEY(`business_id`)REFERENCES `businesses`(`id`)ON DELETE CASCADE,CONSTRAINT `deals_ibfk_4` FOREIGN KEY(`product_id`)REFERENCES `products`(`id`)ON DELETE SET NULL,CONSTRAINT `deals_ibfk_6` FOREIGN KEY(`team_id`)REFERENCES `teams`(`id`)ON DELETE SET NULL)ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Deals/transactions tracking for sales activities';

CREATE TABLE `event_contacts`(`id` int NOT NULL AUTO_INCREMENT,`event_id` int NOT NULL,`contact_id` int NOT NULL,`notes` text,`added_by` int NOT NULL,`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(`id`),UNIQUE KEY `unique_event_contact`(`event_id`,`contact_id`),KEY `idx_event_id`(`event_id`),KEY `idx_contact_id`(`contact_id`),KEY `idx_added_by`(`added_by`),CONSTRAINT `event_contacts_ibfk_1` FOREIGN KEY(`event_id`)REFERENCES `events`(`id`)ON DELETE CASCADE,CONSTRAINT `event_contacts_ibfk_2` FOREIGN KEY(`contact_id`)REFERENCES `contacts`(`id`)ON DELETE CASCADE,CONSTRAINT `event_contacts_ibfk_3` FOREIGN KEY(`added_by`)REFERENCES `users`(`id`)ON DELETE CASCADE)ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `event_types`(`id` int NOT NULL AUTO_INCREMENT,`nama_event_type` varchar(100)NOT NULL,`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(`id`),UNIQUE KEY `unique_nama_event_type`(`nama_event_type`),KEY `idx_nama_event_type`(`nama_event_type`))ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `events`(`id` int NOT NULL AUTO_INCREMENT,`name` varchar(255)NOT NULL,`description` text,`event_date` date NOT NULL,`event_type` varchar(100)DEFAULT NULL,`location` varchar(255)DEFAULT NULL,`kota` varchar(255)DEFAULT NULL,`kecamatan` varchar(255)DEFAULT NULL,`created_by` int NOT NULL,`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,`target_min_age` int DEFAULT NULL,`target_max_age` int DEFAULT NULL,`target_gender` varchar(20)DEFAULT NULL,`target_job_names` text,`target_cities` text,`target_kecamatan` text,`criteria_match_type` enum('ALL','ANY')DEFAULT 'ALL',`auto_target_enabled` tinyint(1)DEFAULT '0',PRIMARY KEY(`id`),KEY `idx_event_date`(`event_date`),KEY `idx_event_type`(`event_type`),KEY `idx_location`(`location`),KEY `idx_created_by`(`created_by`),CONSTRAINT `events_ibfk_1` FOREIGN KEY(`created_by`)REFERENCES `users`(`id`)ON DELETE CASCADE)ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `ingredients`(`id` int NOT NULL AUTO_INCREMENT,`ingredient_code` varchar(50)CHARACTER SET utf8mb4 NOT NULL,`nama` varchar(255)CHARACTER SET utf8mb4 NOT NULL,`kategori` varchar(100)CHARACTER SET utf8mb4 NOT NULL,`satuan_beli` varchar(50)CHARACTER SET utf8mb4 NOT NULL,`isi_satuan_beli` decimal(10,2)NOT NULL,`satuan_keluar` varchar(50)CHARACTER SET utf8mb4 NOT NULL,`harga_beli` int NOT NULL,`stok_min` int DEFAULT '0',`status` enum('active','inactive')CHARACTER SET utf8mb4 DEFAULT 'active',`business_id` int NOT NULL,`created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(`id`),UNIQUE KEY `unique_ingredient_code_business`(`ingredient_code`,`business_id`),KEY `business_id`(`business_id`),CONSTRAINT `ingredients_ibfk_1` FOREIGN KEY(`business_id`)REFERENCES `businesses`(`id`)ON DELETE CASCADE)ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `kartu_keluarga`(`id` int NOT NULL AUTO_INCREMENT,`no_kk` varchar(20)NOT NULL,`created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(`id`),UNIQUE KEY `no_kk`(`no_kk`))ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `leasing_companies`(`id` int NOT NULL AUTO_INCREMENT,`name` varchar(100)NOT NULL,`description` text,`is_active` tinyint(1)DEFAULT '1',`created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(`id`))ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `management_groups`(`id` int NOT NULL AUTO_INCREMENT,`name` varchar(255)CHARACTER SET utf8mb4 NOT NULL,`permission_name` varchar(255)CHARACTER SET utf8mb4 NOT NULL,`description` mediumtext CHARACTER SET utf8mb4,`organization_id` int NOT NULL,`manager_user_id` int DEFAULT NULL,`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(`id`),KEY `idx_management_groups_organization`(`organization_id`),KEY `idx_management_groups_manager`(`manager_user_id`),CONSTRAINT `management_groups_ibfk_1` FOREIGN KEY(`organization_id`)REFERENCES `organizations`(`id`)ON DELETE CASCADE,CONSTRAINT `management_groups_ibfk_2` FOREIGN KEY(`manager_user_id`)REFERENCES `users`(`id`)ON DELETE SET NULL)ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `notes`(`id` int NOT NULL AUTO_INCREMENT,`content` text NOT NULL,`kk_id` int DEFAULT NULL,`ktp_id` int DEFAULT NULL,`created_by` int NOT NULL,`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(`id`),KEY `idx_kk_id`(`kk_id`),KEY `idx_ktp_id`(`ktp_id`),KEY `idx_created_by`(`created_by`),KEY `idx_created_at`(`created_at`),CONSTRAINT `notes_ibfk_1` FOREIGN KEY(`kk_id`)REFERENCES `kartu_keluarga`(`id`)ON DELETE CASCADE,CONSTRAINT `notes_ibfk_2` FOREIGN KEY(`ktp_id`)REFERENCES `contacts`(`id`)ON DELETE CASCADE,CONSTRAINT `notes_ibfk_3` FOREIGN KEY(`created_by`)REFERENCES `users`(`id`)ON DELETE CASCADE)ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `notification_logs`(`id` int NOT NULL AUTO_INCREMENT,`user_id` int NOT NULL,`subscription_id` int DEFAULT NULL,`title` varchar(255)NOT NULL,`body` text NOT NULL,`notification_type` enum('sales_alert','system','marketing','reminder')DEFAULT 'system',`sent_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,`clicked_at` timestamp NULL DEFAULT NULL,`dismissed_at` timestamp NULL DEFAULT NULL,`status` enum('sent','delivered','clicked','dismissed','failed')DEFAULT 'sent',`error_message` text,PRIMARY KEY(`id`),KEY `subscription_id`(`subscription_id`),KEY `idx_user_id`(`user_id`),KEY `idx_sent_at`(`sent_at`),KEY `idx_status`(`status`),KEY `idx_notification_type`(`notification_type`),CONSTRAINT `notification_logs_ibfk_1` FOREIGN KEY(`user_id`)REFERENCES `users`(`id`)ON DELETE CASCADE,CONSTRAINT `notification_logs_ibfk_2` FOREIGN KEY(`subscription_id`)REFERENCES `push_subscriptions`(`id`)ON DELETE SET NULL)ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `notification_preferences`(`id` int NOT NULL AUTO_INCREMENT,`user_id` int NOT NULL,`sales_alerts` tinyint(1)DEFAULT '1',`system_notifications` tinyint(1)DEFAULT '1',`marketing_notifications` tinyint(1)DEFAULT '0',`reminder_notifications` tinyint(1)DEFAULT '1',`created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(`id`),UNIQUE KEY `unique_user_preferences`(`user_id`),CONSTRAINT `notification_preferences_ibfk_1` FOREIGN KEY(`user_id`)REFERENCES `users`(`id`)ON DELETE CASCADE)ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `omset`(`id` int NOT NULL AUTO_INCREMENT,`business_id` int NOT NULL,`date` date NOT NULL,`regular` bigint DEFAULT NULL,`ojol` bigint DEFAULT NULL,`event` bigint DEFAULT NULL,`delivery` bigint DEFAULT NULL,`fitness` bigint DEFAULT NULL,`pool` bigint DEFAULT NULL,`user_id` int NOT NULL,`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(`id`),UNIQUE KEY `unique_omset_entry`(`user_id`,`business_id`,`created_at`),KEY `idx_business_date`(`business_id`,`date`),KEY `idx_date`(`date`),CONSTRAINT `omset_ibfk_1` FOREIGN KEY(`business_id`)REFERENCES `businesses`(`id`),CONSTRAINT `omset_ibfk_2` FOREIGN KEY(`user_id`)REFERENCES `users`(`id`))ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb3;

CREATE TABLE `organization_invitations`(`id` int NOT NULL AUTO_INCREMENT,`organization_id` int NOT NULL,`email` varchar(255)NOT NULL,`role_id` int NOT NULL,`token` varchar(255)NOT NULL,`invited_by` int NOT NULL,`expires_at` datetime NOT NULL,`accepted_at` datetime DEFAULT NULL,`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(`id`),UNIQUE KEY `token`(`token`),KEY `organization_id`(`organization_id`),KEY `invited_by`(`invited_by`),KEY `role_id`(`role_id`),CONSTRAINT `organization_invitations_ibfk_1` FOREIGN KEY(`organization_id`)REFERENCES `organizations`(`id`)ON DELETE CASCADE,CONSTRAINT `organization_invitations_ibfk_2` FOREIGN KEY(`invited_by`)REFERENCES `users`(`id`),CONSTRAINT `organization_invitations_ibfk_3` FOREIGN KEY(`role_id`)REFERENCES `roles`(`id`))ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `organizations`(`id` int NOT NULL AUTO_INCREMENT,`name` varchar(255)NOT NULL,`slug` varchar(100)NOT NULL,`owner_user_id` int NOT NULL,`subscription_status` enum('trial','active','inactive','cancelled')DEFAULT 'trial',`subscription_plan` varchar(50)DEFAULT 'basic',`trial_ends_at` datetime DEFAULT NULL,`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(`id`),UNIQUE KEY `slug`(`slug`),KEY `owner_user_id`(`owner_user_id`),CONSTRAINT `organizations_ibfk_1` FOREIGN KEY(`owner_user_id`)REFERENCES `users`(`id`))ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb3;

CREATE TABLE `payment_methods`(`id` int NOT NULL AUTO_INCREMENT,`name` varchar(50)CHARACTER SET utf8mb4 NOT NULL,`code` varchar(20)CHARACTER SET utf8mb4 NOT NULL,`description` text CHARACTER SET utf8mb4,`is_active` tinyint(1)DEFAULT '1',`requires_additional_info` tinyint(1)DEFAULT '0',`created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(`id`),UNIQUE KEY `code`(`code`))ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `pekerjaan`(`id` int NOT NULL AUTO_INCREMENT,`nama_pekerjaan` varchar(255)NOT NULL,`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(`id`),UNIQUE KEY `nama_pekerjaan`(`nama_pekerjaan`))ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `permission_categories`(`id` int NOT NULL AUTO_INCREMENT,`name` varchar(50)NOT NULL,`description` varchar(255)DEFAULT NULL,`organization_id` int DEFAULT NULL,`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(`id`),UNIQUE KEY `name`(`name`),KEY `permission_categories_ibfk_1`(`organization_id`),CONSTRAINT `permission_categories_ibfk_1` FOREIGN KEY(`organization_id`)REFERENCES `organizations`(`id`)ON DELETE CASCADE)ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb3;

CREATE TABLE `permissions`(`id` int NOT NULL AUTO_INCREMENT,`name` varchar(50)NOT NULL,`description` varchar(255)DEFAULT NULL,`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,`category_id` int DEFAULT NULL,`organization_id` int DEFAULT NULL,`business_id` int DEFAULT NULL,`status` enum('active','inactive')NOT NULL DEFAULT 'active',PRIMARY KEY(`id`),UNIQUE KEY `name`(`name`),KEY `category_id`(`category_id`),KEY `idx_permissions_organization`(`organization_id`),KEY `idx_permissions_status`(`status`),KEY `idx_permissions_business`(`business_id`),CONSTRAINT `permissions_ibfk_1` FOREIGN KEY(`category_id`)REFERENCES `permission_categories`(`id`)ON DELETE SET NULL,CONSTRAINT `permissions_ibfk_2` FOREIGN KEY(`organization_id`)REFERENCES `organizations`(`id`)ON DELETE CASCADE,CONSTRAINT `permissions_ibfk_3` FOREIGN KEY(`business_id`)REFERENCES `businesses`(`id`)ON DELETE SET NULL)ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb3;

CREATE TABLE `printer1_audit_log`(`id` bigint unsigned NOT NULL AUTO_INCREMENT,`transaction_id` varchar(32)NOT NULL,`printer1_receipt_number` int NOT NULL,`global_counter` int DEFAULT NULL,`printed_at` datetime NOT NULL,`printed_at_epoch` bigint NOT NULL,`synced_at` datetime DEFAULT NULL,`reprint_count` int DEFAULT '0',`is_reprint` int DEFAULT '0',PRIMARY KEY(`id`),UNIQUE KEY `uk_printer1_audit`(`transaction_id`,`printer1_receipt_number`,`printed_at_epoch`),KEY `idx_printer1_printed_at`(`printed_at_epoch`))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `printer2_audit_log`(`id` bigint unsigned NOT NULL AUTO_INCREMENT,`business_id` int DEFAULT NULL,`printer2_receipt_number` int NOT NULL,`print_mode` enum('auto','manual')NOT NULL,`cycle_number` int DEFAULT NULL,`printed_by_user_id` int DEFAULT NULL,`printed_at` datetime NOT NULL,`printed_at_epoch` bigint NOT NULL,`transaction_id` varchar(36)NOT NULL,`global_counter` int DEFAULT NULL,`synced_at` datetime DEFAULT NULL,`reprint_count` int DEFAULT '0',`is_reprint` int DEFAULT '0',PRIMARY KEY(`id`),UNIQUE KEY `uk_printer2_audit`(`transaction_id`,`printer2_receipt_number`,`printed_at_epoch`),KEY `idx_p2_audit_mode`(`print_mode`),KEY `idx_p2_audit_time`(`printed_at_epoch`),KEY `fk_p2_audit_user`(`printed_by_user_id`),KEY `fk_p2_audit_business`(`business_id`),CONSTRAINT `fk_p2_audit_business` FOREIGN KEY(`business_id`)REFERENCES `businesses`(`id`)ON DELETE SET NULL,CONSTRAINT `fk_p2_audit_tx` FOREIGN KEY(`transaction_id`)REFERENCES `transactions`(`uuid_id`)ON DELETE CASCADE,CONSTRAINT `fk_p2_audit_user` FOREIGN KEY(`printed_by_user_id`)REFERENCES `users`(`id`)ON DELETE SET NULL)ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `printer_audit_log`(`id` bigint unsigned NOT NULL AUTO_INCREMENT,`uuid_transaction_id` varchar(36)NOT NULL,`business_id` int DEFAULT NULL,`printer_type` enum('receipt','receiptize','label')NOT NULL,`print_mode` enum('auto','manual')DEFAULT NULL,`printer_receipt_number` int DEFAULT NULL,`cycle_number` int DEFAULT NULL,`printed_by_user_id` int DEFAULT NULL,`printed_at` datetime NOT NULL,`printed_at_epoch` bigint NOT NULL,`meta_json` json DEFAULT NULL,PRIMARY KEY(`id`),KEY `idx_printer_audit_uuid`(`uuid_transaction_id`),KEY `idx_printer_audit_type`(`printer_type`),KEY `idx_printer_audit_time`(`printed_at_epoch`),KEY `fk_printer_audit_user`(`printed_by_user_id`),KEY `fk_printer_audit_business`(`business_id`),CONSTRAINT `fk_printer_audit_business` FOREIGN KEY(`business_id`)REFERENCES `businesses`(`id`)ON DELETE SET NULL,CONSTRAINT `fk_printer_audit_tx_uuid` FOREIGN KEY(`uuid_transaction_id`)REFERENCES `transactions`(`uuid_id`)ON DELETE CASCADE,CONSTRAINT `fk_printer_audit_user` FOREIGN KEY(`printed_by_user_id`)REFERENCES `users`(`id`)ON DELETE SET NULL)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `printer_audits`(`id` int NOT NULL AUTO_INCREMENT,`transaction_uuid` varchar(255)NOT NULL,`printer_type` varchar(50)NOT NULL,`status` varchar(50)DEFAULT 'success',`printed_at` datetime DEFAULT NULL,`error_message` text,`business_id` int DEFAULT NULL,`created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(`id`),KEY `idx_transaction_printer`(`transaction_uuid`,`printer_type`))ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `printer_daily_counters`(`id` int NOT NULL AUTO_INCREMENT,`printer_type` varchar(50)NOT NULL,`business_id` int NOT NULL,`date` date NOT NULL,`counter` int NOT NULL DEFAULT '0',`updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,`created_at` datetime DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(`id`),UNIQUE KEY `unique_counter`(`printer_type`,`business_id`,`date`),KEY `idx_business`(`business_id`),KEY `idx_date`(`date`),KEY `idx_printer`(`printer_type`))ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `product_businesses`(`product_id` int NOT NULL,`business_id` int NOT NULL,PRIMARY KEY(`product_id`,`business_id`),KEY `business_id`(`business_id`),CONSTRAINT `product_businesses_ibfk_1` FOREIGN KEY(`product_id`)REFERENCES `products`(`id`)ON DELETE CASCADE,CONSTRAINT `product_businesses_ibfk_2` FOREIGN KEY(`business_id`)REFERENCES `businesses`(`id`)ON DELETE CASCADE)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `product_customization_options`(`id` int NOT NULL AUTO_INCREMENT,`type_id` int NOT NULL,`name` varchar(100)NOT NULL,`price_adjustment` decimal(10,2)DEFAULT '0.00',`display_order` int DEFAULT '0',`status` enum('active','inactive')DEFAULT 'active',PRIMARY KEY(`id`),KEY `type_id`(`type_id`),CONSTRAINT `product_customization_options_ibfk_1` FOREIGN KEY(`type_id`)REFERENCES `product_customization_types`(`id`))ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `product_customization_types`(`id` int NOT NULL AUTO_INCREMENT,`name` varchar(100)NOT NULL,`selection_mode` enum('single','multiple')NOT NULL,`display_order` int DEFAULT '0',PRIMARY KEY(`id`))ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `product_customizations`(`id` int NOT NULL AUTO_INCREMENT,`product_id` int NOT NULL,`customization_type_id` int NOT NULL,PRIMARY KEY(`id`),KEY `product_id`(`product_id`),KEY `customization_type_id`(`customization_type_id`),CONSTRAINT `product_customizations_ibfk_1` FOREIGN KEY(`product_id`)REFERENCES `products`(`id`),CONSTRAINT `product_customizations_ibfk_2` FOREIGN KEY(`customization_type_id`)REFERENCES `product_customization_types`(`id`))ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `products`(`id` int NOT NULL AUTO_INCREMENT,`menu_code` varchar(255)CHARACTER SET utf8mb4 DEFAULT NULL,`nama` varchar(255)CHARACTER SET utf8mb4 NOT NULL,`satuan` varchar(50)CHARACTER SET utf8mb4 NOT NULL,`category1_id` int DEFAULT NULL,`category2_id` int DEFAULT NULL,`keterangan` text CHARACTER SET utf8mb4,`harga_beli` decimal(10,2)DEFAULT NULL,`ppn` decimal(5,2)DEFAULT NULL,`harga_jual` int DEFAULT NULL,`harga_khusus` decimal(10,2)DEFAULT NULL,`harga_online` decimal(10,2)DEFAULT NULL,`harga_gofood` int DEFAULT NULL,`harga_grabfood` int DEFAULT NULL,`harga_shopeefood` int DEFAULT NULL,`harga_tiktok` int DEFAULT NULL,`harga_qpon` int DEFAULT NULL,`fee_kerja` decimal(10,2)DEFAULT NULL,`image_url` varchar(255)CHARACTER SET utf8mb4 DEFAULT NULL,`status` enum('active','inactive')CHARACTER SET utf8mb4 DEFAULT 'active',`created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,`has_customization` tinyint(1)DEFAULT '0',`is_bundle` tinyint(1)DEFAULT '0',PRIMARY KEY(`id`),UNIQUE KEY `unique_menu_code_business`(`menu_code`),KEY `idx_status`(`status`),KEY `idx_products_harga_beli`(`harga_beli`),KEY `idx_products_harga_khusus`(`harga_khusus`),KEY `idx_products_harga_online`(`harga_online`),KEY `idx_products_category1`(`category1_id`),KEY `idx_products_category2`(`category2_id`),CONSTRAINT `fk_products_category1` FOREIGN KEY(`category1_id`)REFERENCES `category1`(`id`)ON DELETE SET NULL,CONSTRAINT `fk_products_category2` FOREIGN KEY(`category2_id`)REFERENCES `category2`(`id`)ON DELETE SET NULL)ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Restaurant Products';

CREATE TABLE `push_subscriptions`(`id` int NOT NULL AUTO_INCREMENT,`user_id` int NOT NULL,`endpoint` varchar(500)NOT NULL,`p256dh_key` varchar(255)NOT NULL,`auth_key` varchar(255)NOT NULL,`user_agent` text,`created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,`is_active` tinyint(1)DEFAULT '1',PRIMARY KEY(`id`),UNIQUE KEY `unique_endpoint`(`endpoint`),KEY `idx_user_id`(`user_id`),KEY `idx_active`(`is_active`),CONSTRAINT `push_subscriptions_ibfk_1` FOREIGN KEY(`user_id`)REFERENCES `users`(`id`)ON DELETE CASCADE)ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `role_permissions`(`role_id` int NOT NULL,`permission_id` int NOT NULL,`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(`role_id`,`permission_id`),KEY `permission_id`(`permission_id`),CONSTRAINT `role_permissions_ibfk_1` FOREIGN KEY(`role_id`)REFERENCES `roles`(`id`)ON DELETE CASCADE ON UPDATE CASCADE,CONSTRAINT `role_permissions_ibfk_2` FOREIGN KEY(`permission_id`)REFERENCES `permissions`(`id`)ON DELETE CASCADE ON UPDATE CASCADE)ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

CREATE TABLE `roles`(`id` int NOT NULL AUTO_INCREMENT,`name` varchar(50)NOT NULL,`description` varchar(255)DEFAULT NULL,`organization_id` int DEFAULT NULL,`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(`id`),UNIQUE KEY `name`(`name`),KEY `idx_roles_organization`(`organization_id`),CONSTRAINT `roles_ibfk_1` FOREIGN KEY(`organization_id`)REFERENCES `organizations`(`id`)ON DELETE CASCADE)ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb3;

CREATE TABLE `sessions`(`id` varchar(255)NOT NULL,`session_token` varchar(255)NOT NULL,`user_id` varchar(255)NOT NULL,`expires` datetime NOT NULL,PRIMARY KEY(`id`),UNIQUE KEY `session_token`(`session_token`),KEY `user_id`(`user_id`))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `shifts`(`id` int NOT NULL AUTO_INCREMENT,`uuid_id` char(36)CHARACTER SET utf8mb4 NOT NULL,`business_id` int NOT NULL,`user_id` int NOT NULL,`user_name` varchar(255)CHARACTER SET utf8mb4 NOT NULL,`shift_start` datetime NOT NULL,`shift_end` datetime DEFAULT NULL,`modal_awal` decimal(15,2)DEFAULT '0.00',`kas_akhir` decimal(15,2)DEFAULT NULL,`kas_expected` decimal(15,2)DEFAULT NULL,`kas_selisih` decimal(15,2)DEFAULT NULL,`kas_selisih_label` enum('balanced','plus','minus')CHARACTER SET utf8mb4 NOT NULL DEFAULT 'balanced',`cash_sales_total` decimal(15,2)DEFAULT NULL,`cash_refund_total` decimal(15,2)DEFAULT NULL,`status` varchar(50)CHARACTER SET utf8mb4 DEFAULT 'active',`created_at` datetime DEFAULT CURRENT_TIMESTAMP,`updated_at` bigint DEFAULT NULL,`synced_at` bigint DEFAULT NULL,PRIMARY KEY(`id`),UNIQUE KEY `idx_shifts_uuid`(`uuid_id`),KEY `idx_shifts_business_user`(`business_id`,`user_id`),KEY `idx_shifts_status`(`status`))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `source`(`id` int NOT NULL AUTO_INCREMENT,`source_name` varchar(255)NOT NULL,`created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(`id`),UNIQUE KEY `source_name`(`source_name`))ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `tags`(`id` int NOT NULL AUTO_INCREMENT,`name` varchar(50)NOT NULL,`description` text,`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(`id`))ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb3;

CREATE TABLE `team_activity_logs`(`id` int NOT NULL AUTO_INCREMENT,`team_id` int NOT NULL,`user_id` int NOT NULL,`action` varchar(50)NOT NULL,`details` text,`metadata` json DEFAULT NULL,`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(`id`),KEY `idx_team_activity_team`(`team_id`),KEY `idx_team_activity_user`(`user_id`),KEY `idx_team_activity_action`(`action`),KEY `idx_team_activity_created`(`created_at`),CONSTRAINT `team_activity_logs_ibfk_1` FOREIGN KEY(`team_id`)REFERENCES `teams`(`id`)ON DELETE CASCADE,CONSTRAINT `team_activity_logs_ibfk_2` FOREIGN KEY(`user_id`)REFERENCES `users`(`id`)ON DELETE CASCADE)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Team-specific activity tracking';

CREATE TABLE `team_members`(`id` int NOT NULL AUTO_INCREMENT,`team_id` int NOT NULL,`user_id` int NOT NULL,`role` enum('member','lead','admin')DEFAULT 'member',`joined_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,`left_at` timestamp NULL DEFAULT NULL,`is_active` tinyint(1)DEFAULT '1',`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(`id`),UNIQUE KEY `unique_active_team_member`(`team_id`,`user_id`),KEY `idx_team_members_team`(`team_id`),KEY `idx_team_members_user`(`user_id`),KEY `idx_team_members_active`(`is_active`),CONSTRAINT `team_members_ibfk_1` FOREIGN KEY(`team_id`)REFERENCES `teams`(`id`)ON DELETE CASCADE,CONSTRAINT `team_members_ibfk_2` FOREIGN KEY(`user_id`)REFERENCES `users`(`id`)ON DELETE CASCADE)ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Team membership tracking';

CREATE TABLE `team_metrics`(`id` int NOT NULL AUTO_INCREMENT,`team_id` int NOT NULL,`metric_date` date NOT NULL,`deals_created` int DEFAULT '0',`deals_won` int DEFAULT '0',`deals_lost` int DEFAULT '0',`total_revenue` decimal(15,2)DEFAULT '0.00',`contacts_added` int DEFAULT '0',`followups_completed` int DEFAULT '0',`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(`id`),UNIQUE KEY `unique_team_metric_date`(`team_id`,`metric_date`),KEY `idx_team_metrics_team`(`team_id`),KEY `idx_team_metrics_date`(`metric_date`),CONSTRAINT `team_metrics_ibfk_1` FOREIGN KEY(`team_id`)REFERENCES `teams`(`id`)ON DELETE CASCADE)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Daily team performance metrics';

CREATE TABLE `team_permissions`(`id` int NOT NULL AUTO_INCREMENT,`team_id` int NOT NULL,`permission_name` varchar(100)NOT NULL,`can_view` tinyint(1)DEFAULT '1',`can_edit` tinyint(1)DEFAULT '0',`can_delete` tinyint(1)DEFAULT '0',`can_assign` tinyint(1)DEFAULT '0',`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(`id`),UNIQUE KEY `unique_team_permission`(`team_id`,`permission_name`),KEY `idx_team_permissions_team`(`team_id`),CONSTRAINT `team_permissions_ibfk_1` FOREIGN KEY(`team_id`)REFERENCES `teams`(`id`)ON DELETE CASCADE)ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Team-specific permissions';

CREATE TABLE `teams`(`id` int NOT NULL AUTO_INCREMENT,`name` varchar(255)NOT NULL,`description` text,`organization_id` int NOT NULL,`team_lead_id` int DEFAULT NULL,`business_id` int DEFAULT NULL,`color` varchar(7)DEFAULT '#3B82F6',`is_active` tinyint(1)DEFAULT '1',`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(`id`),KEY `idx_teams_organization`(`organization_id`),KEY `idx_teams_lead`(`team_lead_id`),KEY `idx_teams_business`(`business_id`),KEY `idx_teams_active`(`is_active`),CONSTRAINT `teams_ibfk_1` FOREIGN KEY(`organization_id`)REFERENCES `organizations`(`id`)ON DELETE CASCADE,CONSTRAINT `teams_ibfk_2` FOREIGN KEY(`team_lead_id`)REFERENCES `users`(`id`)ON DELETE SET NULL,CONSTRAINT `teams_ibfk_3` FOREIGN KEY(`business_id`)REFERENCES `businesses`(`id`)ON DELETE SET NULL)ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Teams within organizations';

CREATE TABLE `transaction_item_customization_options`(`id` int NOT NULL AUTO_INCREMENT,`transaction_item_customization_id` int NOT NULL,`customization_option_id` int NOT NULL,`option_name` varchar(255)NOT NULL,`price_adjustment` decimal(15,2)NOT NULL DEFAULT '0.00',`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(`id`),KEY `idx_transaction_item_customization`(`transaction_item_customization_id`),KEY `idx_customization_option`(`customization_option_id`),KEY `idx_option_name`(`option_name`),KEY `idx_tico_customization_option`(`transaction_item_customization_id`,`customization_option_id`),CONSTRAINT `fk_tico_customization_option` FOREIGN KEY(`customization_option_id`)REFERENCES `product_customization_options`(`id`)ON DELETE CASCADE,CONSTRAINT `fk_tico_transaction_item_customization` FOREIGN KEY(`transaction_item_customization_id`)REFERENCES `transaction_item_customizations`(`id`)ON DELETE CASCADE)ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Stores selected customization options for transaction items';

CREATE TABLE `transaction_item_customizations`(`id` int NOT NULL AUTO_INCREMENT,`transaction_item_id` int NOT NULL,`uuid_transaction_item_id` varchar(255)DEFAULT NULL,`customization_type_id` int NOT NULL,`bundle_product_id` int DEFAULT NULL,`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(`id`),KEY `idx_transaction_item`(`transaction_item_id`),KEY `idx_uuid_transaction_item`(`uuid_transaction_item_id`),KEY `idx_customization_type`(`customization_type_id`),KEY `idx_tic_item_type`(`transaction_item_id`,`customization_type_id`),KEY `idx_tic_bundle_product`(`bundle_product_id`),KEY `idx_tic_item_bundle`(`transaction_item_id`,`bundle_product_id`),CONSTRAINT `fk_tic_customization_type` FOREIGN KEY(`customization_type_id`)REFERENCES `product_customization_types`(`id`)ON DELETE CASCADE,CONSTRAINT `fk_tic_transaction_item` FOREIGN KEY(`transaction_item_id`)REFERENCES `transaction_items`(`id`)ON DELETE CASCADE)ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Links transaction items to customization types';

CREATE TABLE `transaction_items`(`id` int NOT NULL AUTO_INCREMENT,`uuid_id` varchar(36)NOT NULL,`transaction_id` int NOT NULL,`uuid_transaction_id` varchar(36)NOT NULL,`product_id` int NOT NULL,`quantity` int NOT NULL DEFAULT '1',`unit_price` decimal(15,2)NOT NULL,`total_price` decimal(15,2)NOT NULL,`custom_note` text,`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,`bundle_selections_json` json DEFAULT NULL,`production_started_at` timestamp NULL DEFAULT NULL,`production_status` enum('preparing','finished')DEFAULT NULL,`production_finished_at` timestamp NULL DEFAULT NULL,PRIMARY KEY(`id`),UNIQUE KEY `uuid_id`(`uuid_id`),KEY `idx_transaction_items_transaction`(`transaction_id`),KEY `idx_transaction_items_product`(`product_id`),KEY `idx_transaction_items_created`(`created_at`),KEY `fk_transaction_items_transaction_uuid`(`uuid_transaction_id`),KEY `idx_transaction_items_production_status`(`production_status`),CONSTRAINT `fk_transaction_items_product` FOREIGN KEY(`product_id`)REFERENCES `products`(`id`)ON DELETE CASCADE,CONSTRAINT `fk_transaction_items_transaction_uuid` FOREIGN KEY(`uuid_transaction_id`)REFERENCES `transactions`(`uuid_id`)ON DELETE CASCADE)ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Individual items within each transaction';

CREATE TABLE `transaction_refunds`(`id` int NOT NULL AUTO_INCREMENT,`uuid_id` varchar(255)NOT NULL,`transaction_uuid` varchar(255)NOT NULL,`business_id` int NOT NULL,`shift_uuid` char(36)DEFAULT NULL,`refunded_by` int NOT NULL,`refund_amount` decimal(15,2)NOT NULL,`cash_delta` decimal(15,2)NOT NULL DEFAULT '0.00',`payment_method_id` int NOT NULL,`reason` varchar(255)DEFAULT NULL,`note` text,`refund_type` enum('full','partial')DEFAULT 'full',`status` enum('pending','completed','failed')DEFAULT 'completed',`refunded_at` datetime NOT NULL,`synced_at` datetime DEFAULT NULL,`created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(`id`),KEY `fk_transaction_refunds_transaction`(`transaction_uuid`),CONSTRAINT `fk_transaction_refunds_transaction` FOREIGN KEY(`transaction_uuid`)REFERENCES `transactions`(`uuid_id`)ON DELETE CASCADE)ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `transactions`(`id` int NOT NULL AUTO_INCREMENT,`uuid_id` varchar(36)NOT NULL,`business_id` int NOT NULL,`user_id` int NOT NULL,`shift_uuid` char(36)DEFAULT NULL,`payment_method` varchar(50)NOT NULL,`pickup_method` enum('dine-in','take-away')NOT NULL,`total_amount` decimal(15,2)NOT NULL,`voucher_discount` decimal(15,2)DEFAULT '0.00',`voucher_type` enum('none','percent','nominal','free')DEFAULT 'none',`voucher_value` decimal(15,2)DEFAULT NULL,`voucher_label` varchar(255)DEFAULT NULL,`final_amount` decimal(15,2)NOT NULL,`amount_received` decimal(15,2)NOT NULL,`change_amount` decimal(15,2)DEFAULT '0.00',`status` enum('pending','completed','cancelled','refunded')DEFAULT 'completed',`refund_status` enum('none','partial','full')NOT NULL DEFAULT 'none',`refund_total` decimal(15,2)NOT NULL DEFAULT '0.00',`last_refunded_at` datetime DEFAULT NULL,`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,`contact_id` int DEFAULT NULL,`customer_name` varchar(255)DEFAULT NULL,`customer_unit` int DEFAULT NULL,`note` text,`bank_name` varchar(100)DEFAULT NULL,`card_number` varchar(20)DEFAULT NULL,`cl_account_id` int DEFAULT NULL,`cl_account_name` varchar(100)DEFAULT NULL,`bank_id` int DEFAULT NULL,`receipt_number` int DEFAULT NULL,`transaction_type` enum('drinks','bakery')DEFAULT 'drinks',`payment_method_id` int NOT NULL,PRIMARY KEY(`id`),UNIQUE KEY `uuid_id`(`uuid_id`),KEY `idx_transactions_business`(`business_id`),KEY `idx_transactions_user`(`user_id`),KEY `idx_transactions_date`(`created_at`),KEY `idx_transactions_status`(`status`),KEY `idx_transactions_contact`(`contact_id`),KEY `idx_transactions_cl_account`(`cl_account_id`),KEY `idx_transactions_bank`(`bank_name`),KEY `idx_transactions_bank_id`(`bank_id`),KEY `idx_transactions_note`(`note`(100)),KEY `idx_transactions_receipt_number`(`receipt_number`),KEY `idx_transactions_transaction_type`(`transaction_type`),KEY `idx_transactions_daily_receipt`(`business_id`,`created_at`,`receipt_number`),KEY `idx_transactions_payment_method`(`payment_method_id`),KEY `idx_transactions_shift_uuid`(`shift_uuid`),CONSTRAINT `fk_transactions_business` FOREIGN KEY(`business_id`)REFERENCES `businesses`(`id`)ON DELETE CASCADE,CONSTRAINT `fk_transactions_payment_method` FOREIGN KEY(`payment_method_id`)REFERENCES `payment_methods`(`id`),CONSTRAINT `fk_transactions_user` FOREIGN KEY(`user_id`)REFERENCES `users`(`id`)ON DELETE CASCADE)ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='POS Transaction records';

CREATE TABLE `users`(`id` int NOT NULL AUTO_INCREMENT,`email` varchar(255)NOT NULL,`password` varchar(255)DEFAULT NULL,`name` varchar(255)DEFAULT NULL,`googleId` varchar(255)DEFAULT NULL,`createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,`role_id` int NOT NULL,`organization_id` int NOT NULL,PRIMARY KEY(`id`),UNIQUE KEY `email`(`email`),UNIQUE KEY `googleId`(`googleId`),KEY `role_id`(`role_id`),KEY `idx_users_organization`(`organization_id`),KEY `idx_users_email_password`(`email`,`password`),CONSTRAINT `users_ibfk_1` FOREIGN KEY(`role_id`)REFERENCES `roles`(`id`)ON UPDATE CASCADE,CONSTRAINT `users_ibfk_2` FOREIGN KEY(`organization_id`)REFERENCES `organizations`(`id`))ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb3;

CREATE TABLE `verification_tokens`(`identifier` varchar(255)NOT NULL,`token` varchar(255)NOT NULL,`expires` datetime NOT NULL,PRIMARY KEY(`identifier`,`token`))ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `website_visitors`(`id` int NOT NULL AUTO_INCREMENT,`ip_address` varchar(45)NOT NULL,`user_email` varchar(255)DEFAULT NULL,`user_agent` text,`referrer` text,`page_path` varchar(500)DEFAULT NULL,`country` varchar(100)DEFAULT NULL,`city` varchar(100)DEFAULT NULL,`device_type` varchar(50)DEFAULT NULL,`browser` varchar(100)DEFAULT NULL,`os` varchar(100)DEFAULT NULL,`session_id` varchar(255)DEFAULT NULL,`visit_duration` int DEFAULT '0',`tracked_via` varchar(20)DEFAULT 'client-side',`created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,`updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(`id`),KEY `idx_created_at`(`created_at`),KEY `idx_ip_address`(`ip_address`),KEY `idx_session_id`(`session_id`),KEY `idx_page_path`(`page_path`),KEY `idx_user_email`(`user_email`))ENGINE=InnoDB AUTO_INCREMENT DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;